platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%LOCALAPPDATA%\electron\Cache'
  - '%LOCALAPPDATA%\electron-builder\Cache'

install:
  - ps: Install-Product node 12 x64
  - npm install

build_script:
  - npm run publish:gh

test: off

branches:
  only:
    - master
